### ISSUE TITLE
Strange behavior with using .reduce on Combinatorics.combination

### ISSUE THREAD

**Issue by SwiftWinds** [dankogai/js-combinatorics#62] opened 2019-12-24 10:15 UTC
For example, if I were to have:
```js
const Combinatorics = require("js-combinatorics");

const group = ["Penelope", "Brad", "Ivan"];

const cmb = Combinatorics.combination(group, 2);

const pairings = cmb.reduce((acc, pair) => `${acc}${pair[0]} ${pair[1]}, `, "");

console.log(pairings);
```
The output would be `P e, B r, I v, ` instead of the expected `Penelope Brad, Penelope Ivan, Brad Ivan, `.

Is there any specific reason why this happens besides that it's just a bug? Other array methods like `forEach`, `filter`, `map`, etc. seem to work fine; just not `reduce`.

Thanks! 😊

**Comment by SwiftWinds** [comment] 2019-12-24 10:15
A simple example of this bug is in this repo: https://github.com/SwiftWinds/js-combinatorics-bug-with-reduce

**Comment by SwiftWinds** [comment] 2019-12-24 10:19
As a side note, a current workaround would be to have:
```js
const cmb = Combinatorics.combination(group, 2).toArray();
```

**Comment by dankogai** [comment] 2019-12-25 10:12
Hmm.  It is not exactly a bug since `Combinatorics` *does not* define `.reduce()`.  The problem is that combinatorics implements lazy evaluation by redefining `Array` functions.  But  I did not mask out `reduce` so `reduce()` still exists, which iterates through the hidden, opaque storage of `Combinatorics` object, which is generatated via `Object.create(ary.slice())`. 

Anyway it is confusion so I will add `.reduce()`.

**Comment by SwiftWinds** [comment] 2019-12-25 21:48
Ok, thanks! :)

**Comment by dankogai** [comment] 2019-12-26 02:24
Now that I have released version 0.5.5 with `.reduce()` , I'm closing this issue now.

**Closed by dankogai** 2019-12-26 02:24 UTC

**Comment by SwiftWinds** [comment] 2019-12-26 02:27
Awesome.
